export const genericCards = [
  [
    {
      id: 1,
      image: 'GEN_LVL1_01.png',
      actions: ['Alchemy', 'Specialty', 'Trail'],
      phase2: ['1'],
      trashedCards: [6],
      destination: 2,
      movement: 4,
      highest: true,
      attack: 2,
      shield: 0,
      type: 'Blue',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 2,
      image: 'GEN_LVL1_02.png',
      actions: ['Lowest', 'Bomb'],
      phase2: ['1'],
      trashedCards: [1, 5],
      destination: 15,
      movement: 2,
      highest: false,
      attack: 2,
      shield: 0,
      type: 'Purple',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'POTION1DAMAGE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 3,
      image: 'GEN_LVL1_03.png',
      actions: ['Lowest', 'Defense'],
      phase2: ['1'],
      trashedCards: [4, 6],
      destination: 8,
      movement: 1,
      highest: true,
      attack: 1,
      shield: 2,
      type: 'Green',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'RAISESHIELDMAX',
      attackType: 'Bite',
    },
    {
      id: 4,
      image: 'GEN_LVL1_04.png',
      actions: ['Lowest', 'Alchemy', 'Potion'],
      phase2: ['1'],
      trashedCards: [3],
      destination: 11,
      movement: 3,
      highest: false,
      attack: 3,
      shield: 0,
      type: 'Red',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 5,
      image: 'GEN_LVL1_05.png',
      actions: ['Combat', 'Specialty'],
      phase2: ['1'],
      trashedCards: [2],
      destination: 5,
      movement: 3,
      highest: true,
      attack: 2,
      shield: 1,
      type: 'Yellow',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'NONE',
      counter: '2DAMAGE',
      attackType: 'Charge',
    },
    {
      id: 6,
      image: 'GEN_LVL1_06.png',
      actions: ['Combat', 'Potion'],
      phase2: ['1'],
      trashedCards: [1],
      destination: 16,
      movement: 4,
      highest: false,
      attack: 3,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
  [
    {
      id: 7,
      image: 'GEN_LVL2_01.png',
      actions: ['Alchemy', 'Potion'],
      phase2: ['2'],
      trashedCards: [4],
      destination: 18,
      movement: 3,
      highest: true,
      attack: 2,
      shield: 0,
      type: 'Purple',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'POTION2DAMAGE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 8,
      image: 'GEN_LVL2_02.png',
      actions: ['Lowest', 'Defense'],
      phase2: ['Witcher', '2'],
      trashedCards: [4, 5],
      destination: 10,
      movement: 3,
      highest: false,
      attack: 2,
      shield: 2,
      type: 'Green',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 9,
      image: 'GEN_LVL2_03.png',
      actions: ['Highest', 'Specialty'],
      phase2: ['2'],
      trashedCards: [6],
      destination: 1,
      movement: 3,
      highest: true,
      attack: 5,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'DAMAGENORESOLVE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 10,
      image: 'GEN_LVL2_04.png',
      actions: ['Combat', 'Defense'],
      phase2: ['Witcher', '3'],
      trashedCards: [3],
      destination: 6,
      movement: 3,
      highest: false,
      attack: 2,
      shield: 2,
      type: 'Yellow',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 11,
      image: 'GEN_LVL2_05.png',
      actions: ['Potion', 'Potion'],
      phase2: ['3'],
      trashedCards: [1, 2],
      destination: 12,
      movement: 4,
      highest: true,
      attack: 3,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'POTIONATTACK',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 12,
      image: 'GEN_LVL2_06.png',
      actions: ['Defense', 'Potion'],
      phase2: ['3'],
      trashedCards: [2],
      destination: 13,
      movement: 2,
      highest: false,
      attack: 3,
      shield: 0,
      type: 'Purple',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'BOMB2DAMAGEDAMAGENORESOLVE',
      counter: 'NONE',
      attackType: 'Charge',
    },
  ],
  [
    {
      id: 13,
      image: 'GEN_LVL3_01.png',
      actions: ['Combat', 'Trail'],
      phase2: ['Witcher', '4'],
      trashedCards: [3],
      destination: 3,
      movement: 3,
      highest: true,
      attack: 3,
      shield: 2,
      type: 'Green',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'POTIONHEAL1',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 14,
      image: 'GEN_LVL3_02.png',
      actions: ['Specialty', 'Bomb'],
      phase2: ['4'],
      trashedCards: [2],
      destination: 7,
      movement: 3,
      highest: false,
      attack: 6,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'DAMAGENORESOLVE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 15,
      image: 'GEN_LVL3_03.png',
      actions: ['Defense', 'Highest'],
      phase2: ['Meditate', '3'],
      trashedCards: [3, 5],
      destination: 9,
      movement: 1,
      highest: true,
      attack: 3,
      shield: 1,
      type: 'Yellow',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 16,
      image: 'GEN_LVL3_04.png',
      actions: ['Combat', 'Highest'],
      phase2: ['Meditate', '3'],
      trashedCards: [1],
      destination: 17,
      movement: 4,
      highest: false,
      attack: 4,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'BOMBATTACK',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 17,
      image: 'GEN_LVL3_05.png',
      actions: ['Alchemy', 'Trail'],
      phase2: ['Meditate', '3'],
      trashedCards: [6],
      destination: 14,
      movement: 4,
      highest: true,
      attack: 3,
      shield: 0,
      type: 'Purple',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 18,
      image: 'GEN_LVL3_06.png',
      actions: ['Specialty', 'Highest'],
      phase2: ['Meditate', '3'],
      trashedCards: [4, 5],
      destination: 4,
      movement: 4,
      highest: false,
      attack: 0,
      shield: 3,
      type: 'Green',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'POTIONSHIELDDAMAGE',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
]
export const specificCards = [
  [
    {
      id: 19,
      image: 'SPE_LVL1_01.png',
      actions: ['Defense', 'Combat'],
      phase2: ['1'],
      trashedCards: [1],
      destination: 'Monster',
      movement: 99,
      highest: false,
      attack: 3,
      shield: 0,
      type: 'Grey',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'NONE',
      counter: '2DAMAGE',
      attackType: 'Charge',
    },
    {
      id: 20,
      image: 'SPE_LVL1_02.png',
      actions: ['Defense', 'Specialty', 'Trail'],
      phase2: ['1'],
      trashedCards: [2, 3],
      destination: 'Monster',
      movement: 99,
      highest: true,
      attack: 1,
      shield: 2,
      type: 'Grey',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'POTION2DAMAGE',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 21,
      image: 'SPE_LVL1_03.png',
      actions: ['Alchemy', 'Combat'],
      phase2: ['1'],
      trashedCards: [4],
      destination: 'Monster',
      movement: 99,
      highest: false,
      attack: 2,
      shield: 1,
      type: 'Grey',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'HEAL2',
      counter: 'NONE',
      attackType: 'Charge',
    },
  ],
  [
    {
      id: 22,
      image: 'SPE_LVL2_01.png',
      actions: ['Highest', 'Bomb'],
      phase2: ['3'],
      trashedCards: [3, 4],
      destination: 'Monster',
      movement: 99,
      highest: true,
      attack: 3,
      shield: 1,
      type: 'Grey',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'NONE',
      counter: '2DAMAGE',
      attackType: 'Bite',
    },
    {
      id: 23,
      image: 'SPE_LVL2_02.png',
      actions: ['Lowest', 'Potion'],
      phase2: ['3'],
      trashedCards: [1],
      destination: 'Monster',
      movement: 99,
      highest: false,
      attack: 5,
      shield: 0,
      type: 'Grey',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 24,
      image: 'SPE_LVL2_03.png',
      actions: ['Potion', 'Bomb', 'Trail'],
      phase2: ['3'],
      trashedCards: [2],
      destination: 'Monster',
      movement: 99,
      highest: true,
      attack: 2,
      shield: 2,
      type: 'Grey',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'ATTACK',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
  [
    {
      id: 25,
      image: 'SPE_LVL3_01.png',
      actions: ['Highest', 'Trail'],
      phase2: ['2'],
      trashedCards: [4],
      destination: 'Monster',
      movement: 99,
      highest: false,
      attack: 0,
      shield: 0,
      type: 'Grey',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'SPECIAL1',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 26,
      image: 'SPE_LVL3_02.png',
      actions: ['Specialty', 'Alchemy'],
      phase2: ['4'],
      trashedCards: [3],
      destination: 'Monster',
      movement: 99,
      highest: true,
      attack: 0,
      shield: 0,
      type: 'Grey',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'SPECIAL2',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 27,
      image: 'SPE_LVL3_03.png',
      actions: ['Potion', 'Bomb'],
      phase2: ['4'],
      trashedCards: [1, 2],
      destination: 'Monster',
      movement: 99,
      highest: false,
      attack: 0,
      shield: 0,
      type: 'Grey',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'SPECIAL3',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
]
export const skelligeCards = [
  [
    {
      id: 28,
      image: 'SK_LVL1_01.png',
      actions: ['Dagon', 'Bomb', 'Alchemy'],
      phase2: ['Skellige Event 1'],
      trashedCards: [1, 2],
      destination: 21,
      movement: 99,
      highest: false,
      attack: 1,
      shield: 0,
      type: 'Yellow',
      redMutagen: 1,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'POTION2SHIELD',
      counter: 'NONE',
      attackType: 'Bite',
    },
    {
      id: 29,
      image: 'SK_LVL1_02.png',
      actions: ['Dagon', 'Lowest'],
      phase2: ['Skellige Event 2'],
      trashedCards: [3, 4],
      destination: 20,
      movement: 99,
      highest: true,
      attack: 2,
      shield: 0,
      type: 'Blue',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 0,
      special: 'POTION1DAMAGE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 30,
      image: 'SK_LVL1_03.png',
      actions: ['Dagon', 'Alchemy'],
      phase2: ['Skellige Event 3'],
      trashedCards: [5, 6],
      destination: 19,
      movement: 99,
      highest: false,
      attack: 1,
      shield: 0,
      type: 'Purple',
      redMutagen: 0,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'POTION2DAMAGE',
      counter: 'NONE',
      attackType: 'Charge',
    },
  ],
  [
    {
      id: 31,
      image: 'SK_LVL2_01.png',
      actions: ['Dagon', 'Lowest'],
      phase2: ['Skellige Event 4'],
      trashedCards: [3],
      destination: 20,
      movement: 99,
      highest: true,
      attack: 1,
      shield: 2,
      type: 'Green',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'NONE',
      counter: '2DAMAGE',
      attackType: 'Charge',
    },
    {
      id: 32,
      image: 'SK_LVL2_02.png',
      actions: ['Dagon', 'Potion', 'Bomb'],
      phase2: ['Skellige Event 4'],
      trashedCards: [2],
      destination: 21,
      movement: 99,
      highest: false,
      attack: 3,
      shield: 0,
      type: 'Red',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 0,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 33,
      image: 'SK_LVL2_03.png',
      actions: ['Defense'],
      phase2: ['Meditate', '3'],
      trashedCards: [5],
      destination: 19,
      movement: 99,
      highest: true,
      attack: 2,
      shield: 1,
      type: 'Yellow',
      redMutagen: 0,
      blueMutagen: 0,
      greenMutagen: 1,
      special: 'NONE',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
  [
    {
      id: 34,
      image: 'SK_LVL3_01.png',
      actions: ['Potion', 'Bomb'],
      phase2: ['Meditate', '4'],
      trashedCards: [1],
      destination: 21,
      movement: 99,
      highest: false,
      attack: 2,
      shield: 1,
      type: 'Yellow',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'NONE',
      counter: '2DAMAGE',
      attackType: 'Bite',
    },
    {
      id: 35,
      image: 'SK_LVL3_02.png',
      actions: ['Dagon', 'Combat'],
      phase2: ['Meditate', '4'],
      trashedCards: [6],
      destination: 19,
      movement: 99,
      highest: true,
      attack: 'Lvl',
      shield: 0,
      type: 'Red',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'SPECIALSK1',
      counter: 'NONE',
      attackType: 'Charge',
    },
    {
      id: 36,
      image: 'SK_LVL3_03.png',
      actions: ['Lowest'],
      phase2: ['Meditate', '4'],
      trashedCards: [4],
      destination: 20,
      movement: 99,
      highest: false,
      attack: 'Lvl',
      shield: 0,
      type: 'Green',
      redMutagen: 1,
      blueMutagen: 1,
      greenMutagen: 1,
      special: 'SPECIALSK2',
      counter: 'NONE',
      attackType: 'Bite',
    },
  ],
]
export const legendaryHuntCards = [
  {
    id: 37,
    image: 'LH_LVL_3_01.png',
    actions: ['Combat', 'Potion', 'Bomb'],
    phase2: ['Legendary'],
    trashedCards: [3, 6],
    destination: 'Legendary',
    movement: 99,
    highest: false,
    attack: 0,
    shield: 0,
    type: 'Grey',
    redMutagen: 0,
    blueMutagen: 0,
    greenMutagen: 0,
    special: 'NONE',
    counter: 'NONE',
    attackType: '',
  },
  {
    id: 38,
    image: 'LH_LVL_3_02.png',
    actions: ['Alchemy', 'Potion', 'Bomb'],
    phase2: ['Legendary'],
    trashedCards: [2, 4],
    destination: 'Legendary',
    movement: 99,
    highest: true,
    attack: 0,
    shield: 0,
    type: 'Grey',
    redMutagen: 0,
    blueMutagen: 0,
    greenMutagen: 0,
    special: 'NONE',
    counter: 'NONE',
    attackType: '',
  },
  {
    id: 39,
    image: 'LH_LVL_3_03.png',
    actions: ['Defense', 'Poiton', 'Bomb'],
    phase2: ['Legendary'],
    trashedCards: [1, 5],
    destination: 'Legendary',
    movement: 99,
    highest: true,
    attack: 0,
    shield: 0,
    type: 'Grey',
    redMutagen: 0,
    blueMutagen: 0,
    greenMutagen: 0,
    special: 'NONE',
    counter: 'NONE',
    attackType: '',
  },
]
