export const MonsterFights = [
  { id: 1, charge: '3', bite: '4' },
  { id: 2, charge: '4', bite: 'Specialty' },
  { id: 3, charge: '1', bite: 'Combat' },
  { id: 4, charge: 'MonsterLvl', bite: 'MonsterLvlPlus2' },
  { id: 5, charge: '5', bite: 'Alchemy' },
  { id: 6, charge: '1', bite: '3' },
  { id: 7, charge: '2', bite: '3' },
  { id: 8, charge: 'MonsterLvl', bite: '4' },
  { id: 9, charge: '1', bite: '2' },
  { id: 10, charge: 'MonsterLvl', bite: '3' },
  { id: 11, charge: 'MonsterLvl', bite: '4' },
  { id: 12, charge: '4', bite: '2' },
  { id: 13, charge: '3', bite: 'Defense' },
  { id: 14, charge: '3', bite: '5' },
  { id: 15, charge: '2', bite: 'LowerAlchemyByMonsterLevelMinus1' },
  { id: 16, charge: 'MonsterLevelPlus2', bite: 'LowerDefenseByMonsterLevelMinus1' },
  { id: 17, charge: '3', bite: '5' },
  { id: 18, charge: '5', bite: '2' },
  { id: 19, charge: '2', bite: '4' },
  { id: 20, charge: '4', bite: 'LowerCombatByMonsterLevelMinus1' },
  { id: 21, charge: 'Special1OrPassive', bite: 'Special1OrPassive' },
  { id: 22, charge: 'Special2OrPassive', bite: 'Special2OrPassive' },
  { id: 23, charge: 'Special3OrPassive', bite: 'Special3OrPassive' },
  { id: 24, charge: 'Special4OrPassive', bite: 'Special4OrPassive' },
]
